### ISSUE TITLE
HomeySetup.exe crash

### ISSUE THREAD

**Issue by Bumblez** [athombv/node-athom-gui#15]
When I tried to run HomeySetup.exe on my system (Windows 7 Ultimate, 64bit) it crashed right away. I tried it 4 times, and some of these times it appeared to get a little further before it crashed. So I tried a 5th time, and managed to actually install it (although I would appreciate an option to decide where I want to install it). In the SquirrelSetup.log I see two errors during setup:

2016-07-02 08:26:40> UpdateInfo: Couldn't get release notes for:athom-gui-0.1.11-delta.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\Public User\AppData\Local\athom\packages\athom-gui-0.1.11-delta.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__2(ReleaseEntry x)

(could this be the cause of the crash?)
and

2016-07-02 08:27:01> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: Could not find a part of the path 'C:\Users\msbruning\Documents\workspace\athom\node-athom-gui\assets\app-icon\win\app.ico'. ---> System.Net.WebException: Could not find a part of the path 'C:\Users\msbruning\Documents\workspace\athom\node-athom-gui\assets\app-icon\win\app.ico'. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\msbruning\Documents\workspace\athom\node-athom-gui\assets\app-icon\win\app.ico'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   --- End of inner exception stack trace ---
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   at System.Net.FileWebRequest.GetResponseCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__12b.MoveNext()

(there is no user msbruning on my system!)

**Comment by TheMSB** [comment]
@Bumblez Could you please specify what installer version you are using? Also when the installer crashed the first four times, what happened? Did it throw an error?

**Comment by TheMSB** [comment]
@Bumblez I tried some random stuff to see if I could reproduce what I suspected was going on. I only managed to reproduce your error when I tried rapidly launching the setup multiple times before waiting for it.

Could this be the cause of your error?

While unrelated I will look into that strange pathing error that shows up in the log file.

**Comment by Bumblez** [comment]
The installer I used was the HomeySetup.exe that I downloaded from https://nuts.athom.com/
And no, it can not be the 'rapidly launching it multiple times' problem... I had the crash straight away the first time I launched the installer. I double-clicked the installer to launch it, it opened a small popup to confirm that it was installing, then that popup disappeared (I did not click anything), and within a second, this was followed by a Windows popup informing me that an exception had occured (or something like that... sorry, I didn't make a screenshot, or write down the exact message).
I closed that popup, then I tried to find the location where HomeySetup had installed the files (looking for a log file)... that took maybe half a minute, in which I failed to find the installed files on my C drive. Only after that did I run homeysetup.exe a second time... with the same results.

**Comment by Bumblez** [comment]
Well, as described earlier, I eventually managed to run setup successfully, so it's no longer a problem for me. I just hope this helps to make the installer more stable for the future...

**Comment by TheMSB** [comment]
> Well, as described earlier, I eventually managed to run setup successfully, so it's no longer a problem for me. I just hope this helps to make the installer more stable for the future...

I'm sure it will, thank you for bringing this to our attention.
