### ISSUE TITLE
Run Crash on Mac

### ISSUE THREAD

**Issue by soler2000** [athombv/node-athom-gui#16]
When trying to run on my mac I get the following error, running a second time the problem goes away

Uncaught Exception:
Error: Cannot initialize "screen" module before app is ready
    at Error (native)
    at process.atomBinding (/Applications/Homey.app/Contents/Resources/electron.asar/common/init.js:8:22)
    at Object.<anonymous> (/Applications/Homey.app/Contents/Resources/electron.asar/browser/api/screen.js:2:26)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)

**Comment by TheMSB** [comment]
- Dit this happen after your first use at all?
 - Did you launch the app through your Dock? Or Did you run it from your applications folder?

**Comment by soler2000** [comment]
This only happened once after install,   the app was run from the applications folder not the dock
